In [1]:
import pandas as pd
from datetime import date

In [2]:
df = pd.read_csv("reactivos_comercial.csv")

In [3]:
df.head(1).T

                                                  0
id                                             R001
reactivo                      Ácido clorhídrico 37%
formula                                         HCl
categoria                                     Ácido
estado                                      Líquido
masa_molar                                    36.46
pureza_pct                                     95.1
cantidad                                        817
unidad                                           mL
stock_minimo                                    250
precio_100                                    10.15
cantidad_comercial                             1000
precio_unitario                                14.5
ubicacion                            Armario ácidos
peligro                                   Corrosivo
fecha_caducidad                          2030-03-26
ficha_pdf           fichas/acido_clorhidrico_37.pdf
pictograma                pictogramas/corrosivo.png

In [ ]:
def add_units(row):
    if row["estado"] == "Sólido":
        return f"{row.cantidad} g"
    elif row["estado"] == "Líquido":
        return f"{row["cantidad"]} mL"
    else:
        return row["cantidad"]

In [11]:
df.loc[:, ["cantidad", "estado"]].apply(add_units, axis = 0)

AttributeError: 'Series' object has no attribute 'estado'

Conversión a datetime de la columna `fecha_caducidad`

In [4]:
df.fecha_caducidad = pd.to_datetime(df.fecha_caducidad).dt.date

Creación de nuevas columnas

In [5]:
df["valor"] = round(df.cantidad / 100 * df.precio_100, 2)
df["bajo_stock"] = df.cantidad < df.stock_minimo
df["caducado"] = df.fecha_caducidad > date.today()

Renombrado de columnas de archivos

In [6]:
df = df.rename(columns = {"ficha_pdf" : "ficha_url",
                          "pictograma" : "picto_url"})

Generación de la ruta de los archivos

In [7]:
df.ficha_url = "static/" + df.ficha_url
df.picto_url = "static/" + df.picto_url

In [9]:
df.isna().sum()

id                    0
reactivo              0
formula               0
categoria             0
estado                0
masa_molar            0
pureza_pct            0
cantidad              0
unidad                0
stock_minimo          0
precio_100            0
cantidad_comercial    0
precio_unitario       0
ubicacion             0
peligro               0
fecha_caducidad       0
ficha_pdf             0
pictograma            0
dtype: int64

In [8]:
df.sample()

,id,reactivo,formula,categoria,estado,masa_molar,pureza_pct,cantidad,unidad,stock_minimo,precio_100,cantidad_comercial,precio_unitario,ubicacion,peligro,fecha_caducidad,ficha_pdf,pictograma
12,R013,Permanganato de potasio,KMnO4,Sal,Sólido,158.03,96.3,723,g,200,41.75,500,42.5,Estantería general,Comburente,2028-12-26,fichas/permanganato_de_potasio.pdf,pictogramas/comburente.png

In [9]:
df.columns

Index(['id', 'reactivo', 'formula', 'categoria', 'estado', 'masa_molar',
       'pureza_pct', 'cantidad', 'unidad', 'stock_minimo', 'precio_100',
       'ubicacion', 'peligro', 'fecha_caducidad', 'ficha_url', 'picto_url',
       'valor', 'bajo_stock', 'caducado'],
      dtype='object')

In [5]:
df.pictograma.head()

0     pictogramas/corrosivo.png
1     pictogramas/corrosivo.png
2     pictogramas/corrosivo.png
3    pictogramas/inflamable.png
4     pictogramas/irritante.png
Name: pictograma, dtype: str